development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: digitalz_development
  username: digitalz
  password: kirikou5722
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: digitalz_test
  username: digitalz
  password: kirikou5722
  pool: 5
  timeout: 5000